### ISSUE TITLE
bitcoin-indexer

### ISSUE THREAD

**Issue by 0x677261706562616261** [b2network/b2-node#22]
## Goal

Create a module pull bitcoin block and parse transaction, generate state

- [x] #23 
- [x] https://github.com/b2network/b2-node/issues/31
- [x] https://github.com/b2network/b2-node/issues/29
- [x] https://github.com/b2network/b2-node/issues/40
- [x] https://github.com/b2network/b2-node/issues/53
- [x] https://github.com/b2network/b2-node/issues/60
- [ ] https://github.com/b2network/b2-node/issues/62
- [x] https://github.com/b2network/b2-node/issues/78

**Comment by 0x677261706562616261** [comment]
@Stonepapa please help add the lib which could be refered.

**Comment by oxf71** [comment]
- [ ] #23

**Comment by 0x677261706562616261** [comment]
refer to unisat opensource indexer: https://github.com/unisat-wallet/libbrc20-indexer

**Comment by oxf71** [comment]
refer to evm indexer : https://github.com/b2network/b2-node/blob/main/server/indexer_service.go


Is the architecture Reference evm indexer feasible? @0x677261706562616261 @Stonepapa
