### ISSUE TITLE
bitcoin-commiter

### ISSUE THREAD

**Issue by 0x677261706562616261** [b2network/b2-node#5]
- [ ] [https://github.com/b2network/b2-node/issues/4](https://github.com/b2network/b2-node/issues/4)
- [ ] [https://github.com/b2network/b2-node/issues/26](https://github.com/b2network/b2-node/issues/26)
- [ ] [https://github.com/b2network/b2-node/issues/36](https://github.com/b2network/b2-node/issues/36)
- [ ] [https://github.com/b2network/b2-node/issues/41](https://github.com/b2network/b2-node/issues/41)
- [ ] [https://github.com/b2network/b2-node/issues/68](https://github.com/b2network/b2-node/issues/68)

**Comment by 0x677261706562616261** [comment]
[module](https://docs.cosmos.network/main/build/building-modules/intro)

**Comment by Stonepapa** [comment]
commit data:
1. storage path of batch proposals
2. rollup btach proposals txs merkle tree root hash
3. rollup zk proof data
4. previous tapscript hash

**Comment by zhouop0** [comment]
- [ ] [https://github.com/b2network/b2-node/issues/5](https://github.com/b2network/b2-node/issues/5)
